-- AlterTable
ALTER TABLE "DailyTarget" ADD COLUMN     "carbsPct" DOUBLE PRECISION,
ADD COLUMN     "fatPct" DOUBLE PRECISION,
ADD COLUMN     "fiberGrams" DOUBLE PRECISION,
ADD COLUMN     "proteinPct" DOUBLE PRECISION,
ADD COLUMN     "saltGrams" DOUBLE PRECISION;
